---
bibliography: references.bib
---

# Two qubit Clifford group

The two-qubit Clifford group is generated from single-qubit unitaries and the controlled-NOT (CNOT) gate. When implementing the protocol, it's crucial to use a Clifford decomposition that minimizes the number of two-qubit gates, as these generally have lower fidelities than single-qubit gates.

As in the single qubit case, the *exponential decay* should be fit to
$$
F(m)= Ap^m + B
$${#eq-survival-rate}

where $m$ is the number of Cliffords in the sequence, and $A$ and $B$ are parameters related to state preparation and measurement, and $1-p$ is the depolarization rate.

The two-qubit Clifford group can be divided into **four classes** [@corcolesProcessVerificationTwoqubit2013]:  

1. The **Single-qubit Clifford class** that consists of 576 elements ($24^2$) and represents all single-qubit Clifford operations:

    ```qasm
         в”Ңв”Җв”Җв”Җв”Җв”җ
    q_0: в”Ө C1 в”ң
         в”ңв”Җв”Җв”Җв”Җв”Ө
    q_1: в”Ө C1 в”ң
         в””в”Җв”Җв”Җв”Җв”ҳ
    ```

2. The **CNOT-class** that has 5184 elements ($24^2\times 3^2$) and contains all combinations of the following sequence:

    ```qasm
         в”Ңв”Җв”Җв”Җв”Җв”җ     в”Ңв”Җв”Җв”Җв”Җв”җ
    q_0: в”Ө C1 в”ңв”Җв”Җв– в”Җв”Җв”Ө S1 в”ң
         в”ңв”Җв”Җв”Җв”Җв”Өв”Ңв”Җв”ҙв”Җв”җв”ңв”Җв”Җв”Җв”Җв”Ө
    q_1: в”Ө C1 в”ңв”Ө X в”ңв”Ө S1 в”ң
         в””в”Җв”Җв”Җв”Җв”ҳв””в”Җв”Җв”Җв”ҳв””в”Җв”Җв”Җв”Җв”ҳ
    ```

3. The **ISWAP-class** The **third class** also has 5184 elements and contains all combinations of the following sequence:

    ```qasm
         в”Ңв”Җв”Җв”Җв”Җв”җ   в”Ңв”Җв”Җв”Җв”Җв”җ
    q_0: в”Ө C1 в”ңв”Җ*в”Җв”Ө S1 в”ң
         в”ңв”Җв”Җв”Җв”Җв”Ө в”Ӯ в”ңв”Җв”Җв”Җв”Җв”Ө
    q_1: в”Ө C1 в”ңв”Җ*в”Җв”Ө S1 в”ң
         в””в”Җв”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”Җв”ҳ
    ```

4. **SWAP-class**. The **fourth class** is the *SWAP-class* and consists of all 576 ($24^2$) combinations of the following sequence:

    ```qasm
         в”Ңв”Җв”Җв”Җв”Җв”җ
    q_0: в”Ө C1 в”ңв”ҖXв”Җ
         в”ңв”Җв”Җв”Җв”Җв”Ө в”Ӯ
    q_1: в”Ө C1 в”ңв”ҖXв”Җ
         в””в”Җв”Җв”Җв”Җв”ҳ    
    ```

Therefore, there are in total *11 520* elements in the two-qubit Clifford group.

## Gate Decomposition

The decomposition of the two-qubit Clifford group above is the *optimal* in terms of the number of CNOTs. Since an iSWAP requires two CNOTs and a SWAP requires three, the *average number of CNOTs per Clifford operation* is **1.5**. The same holds if we use CZ instead of CNOT as the building block, since the CNOT can be decomposed as a CZ with two Hadamards. The number of single-qubit gates depends on how the single-qubit Cliffords are implemented.

Below follows the *decomposition* of the two-qubit gates in terms of the CZ-gate and single-qubit -gates:

1. **CNOT to CZ**  

    ```qasm
    q_0: в”Җв”Җв– в”Җв”Җ          q_0: в”Җв”Җв”Җв”Җв”Җв”Җв– в”Җв”Җв”Җв”Җв”Җв”Җ    
         в”Ңв”Җв”ҙв”Җв”җ  в”Җв”Җв”Җв”Җ>        в”Ңв”Җв”Җв”Җв”җ в”Ӯ в”Ңв”Җв”Җв”Җв”җ
    q_1: в”Ө X в”ң          q_1: в”Ө H в”ңв”Җв– в”Җв”Ө H в”ң
         в””в”Җв”Җв”Җв”ҳ               в””в”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”ҳ
    ```

2. **iSWAP to CZ**  

    ```qasm
                            global phase: 3ПҖ/2
                             в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җв”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ   в”Ңв”Җв”Җв”Җв”җ   в”Ңв”Җв”Җв”Җв”җ
    q_0: в”Җ*в”Җ            q_0: в”Ө Ry(ПҖ/2) в”ңв”Ө Rx(-ПҖ/2) в”ңв”Җв– в”Җв”Ө H в”ңв”Җв– в”Җв”Ө H в”ң
          в”Ӯ     в”Җв”Җв”Җв”Җ>        в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Өв”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө в”Ӯ в”ңв”Җв”Җв”Җв”Ө в”Ӯ в”ңв”Җв”Җв”Җв”Ө
    q_1: в”Җ*в”Җ            q_1: в”Ө Ry(ПҖ/2) в”ңв”Ө Rx(-ПҖ/2) в”ңв”Җв– в”Җв”Ө H в”ңв”Җв– в”Җв”Ө H в”ң
                             в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳв””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”ҳ
    ```

3. **SWAP to CZ**  

    ```qasm
                            global phase: ПҖ
                             в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ   в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ   в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ   
    q_0: в”ҖXв”Җ            q_0: в”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җв”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җв”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җ
          в”Ӯ     в”Җв”Җв”Җв”Җ>        в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө в”Ӯ в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө в”Ӯ в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө в”Ӯ 
    q_1: в”ҖXв”Җ            q_1: в”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җв”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җв”Ө Rx(ПҖ/2) в”ңв”Җв– в”Җ
                             в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ   в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
    ```

### Interleaved Clifford Randomized Benchmarking

*Interleaved Clifford Randomized Benchmarking* allows estimation of the error associated with an individual Clifford gate. The core idea is to perform two benchmarking experiments: one following the standard Clifford Randomized Benchmarking (RB) method and one with the target Clifford gate interleaved[@lallReviewCollectionMetrics2025].

If the standard RB sequence is:

$$
C_1C_2\ldots C_m C_\mathrm{inverse},
$$

where each $C$ is a Clifford gate, then the interleaved RB sequence introduces the Clifford gate $C_\mathrm{target}$ spaced in between the Clifford gates:

$$
C_1C_\mathrm{target}C_2C_\mathrm{target}\ldots C_mC_\mathrm{target}C'_\mathrm{inverse}
$$

where $C_\mathrm{target}$ is the gate being characterized and must also belong to the Clifford group, and $C'_\mathrm{inverse}$ is the final inverting gate that must be updated to invert the full gate sequence including $C_\mathrm{target}$.

The error of $C_\mathrm{target}$ is thus determined by comparing the decay rates  @eq-survival-rate of the standard Clifford RB and the interleaved Clifford RB experiments.

If the fitted decay parameters from the standard RB and the interleaved RB are denoted by $p$ and $p_\mathrm{interleaved}$ respectively. Then, the interleaved RB gate error for $C_\mathrm{target}$ is found using

$$
r_{C_\mathrm{target}}=\frac{(d-1)(1-\frac{p_\mathrm{interleaved}}{p})}{d}
$$

where $d$ is the dimension of the system (e.g., $d=2^n$ for an $n$-qubit system).