# Configuration Files

## Hardware Configuration file (json):
Here the connection is made between the Qblox cluster physical ports and clocks to the qubits and couplers of the QPU.

The file must be placed at the directory `configs/`

Given a `.csv` file after a mixer calibration the function `...` can create instantly the corresponding `JSON` file.

### Migrating old hardware configurations to match quantify-scheduler>=0.18.0
With quantify-scheduler 0.18.0 there is been introduced a new way on how to structure the hardware configuration file.
If you are having a hardware configuration file, that is structured using the old way, you can use the following script to migrate it to the new structure.
```
python tergite_autocalibration/scripts/migrate_blox_hardware_configuration.py <PATH_TO_HW_CONFIG>
```

## Device Configuration file (toml):

Here we set reasonable initial parameters

## VNA resonator & qubit frequencies

Here we input the initial values for the resonator and qubits frequencies, assumed that they have been acquired through VNA measurements, design targets or previous manual measurements.
`/tergite_acl/config/VNA_values.py`

## Coupler to SPI mapping
