[tool.poetry]
name = "oqs-licensing"
version = "1.0.10"
description = ""
authors = ["Stefan Hill <stefanhi@chalmers.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"