## Operation

The package ships with a command line interface to solve some common tasks that appear quite often.

In the following there are a number of useful commands, but if you want to find out all commands use:
```acli --help```

To delete all redis entries:
```acli node reset -a```

To reset a particular node:
```acli node reset -n <nodename>```

For example to reset the node `rabi_oscillations` run the command:

```acli node reset -n rabi_oscillations```

**To start a new calibration sequence according to the configuration files:**

**```python tergite_acl/scripts/calibration_supervisor.py```**

or

**```acli calibration start```**

## Structure ##
For each calibration node:
compilation -> execution -> post-processing -> redis updating

## Data browsing ##
Datasets are stored in `data_directory`
Can be browsed with the dataset browser (coming soon)

## Development ##
When submitting  contributions, please prepend your commit messages with:
`fix:` for bug fixes
`feat:` for introducing a new feature (e.g. a new measurement node or a new analysis class)
`chore:` for refractoring changes or any change that doesn't affect the functionality of the code
`docs:` for changes in the README, docstrings etc
`test:` or `dev:` for testing or development changes (e.g. profiling scripts)
