name: Deploy Documentation
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Configure Git credentials for GitHub Pages
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: 💾 Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip # Replace ~/.cache/pip with the correct path if not using Ubuntu.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📚 Install package with documentation extras
        run: pip install '.[docs]'

      - name: 🚀 Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force